inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/views/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'

Style/IfUnlessModifier:
  Enabled: false
