sudo: required

language: ruby

services:
  - docker

script:
  - docker-compose run web rake db:setup
  - docker-compose run web rspec 

env:
  global:
    secure: axvjtAqhdh32g9zmUaxd4mu7+iR/ZJaj/hw+Ss5XMJDcCKUSR/BUvqvo7ZFeHN2YGwS8DzCS0Fsr6Axop5mqfzyjVvHDKd4zE+Lm7HW+NUJVoV8khlLeEVX/KYcqWkKNkChxRRbIB3xnqim1H4T2ThKNlzl3wHgFRXdzK/gl57c=

