services:
  base:
    build:
      context: ./
      dockerfile: ./container/base/Dockerfile
  web:
    #image: code.cozy.town/codeforleipzig/stadtratmonitor/develop:latest
    build:
      context: ./
      dockerfile: ./container/develop/Dockerfile
    container_name: stadtratmonitor-web
    volumes:
      - .:/app/
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - OPENSEARCH_URL=${OPENSEARCH_URL:-http://opensearch:9200}
      - APPLICATION_HOST=${APPLICATION_HOST:-localhost}
      - SHARED_IMPORT_SECRET=$SHARED_IMPORT_SECRET
    networks:
      - stadtratmonitor
  opensearch:
    container_name: stadtratmonitor-opensearch
    user: opensearch
    build:
      context: ./
      dockerfile: ./docker/opensearch/Dockerfile
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "127.0.0.1:9215:9200"
    volumes:
      - ${OSDATA:-osdata}:/usr/share/opensearch/data //read, write and execute
      - ./docker/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    command: sh -c "/usr/share/opensearch/bin/opensearch"
    networks:
      - stadtratmonitor
  dashboard:
    restart: always
    image: opensearchproject/opensearch-dashboards:3.4.0
    environment:
      OPENSEARCH_HOSTS: ${OPENSEARCH_URL:-http://opensearch:9200}
      DISABLE_INSTALL_DEMO_CONFIG: "false"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - "./docker/opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
    ports:
      - "5601:5601"

volumes:
  osdata:
networks:
  stadtratmonitor: