# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 655c9e4e14bd341043f268ab4960d182a1d55feb94492888b6dc9854012fea1f8f2ea90c25249431fd7cbd5e329bdfe1d24f1491ac927a3915ee53e3a2391236

test:
  secret_key_base: a348ff0b42d30a74fd26f27f83b8b28a5a97850927838ed180d213c99e4fef5540ae76f31e50d8b7cf8b8dd6413b372a4e217bddd12add35c0e5e66ec42f44a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
