name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: "${{secrets.HEROKU_EMAIL"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stadtratmonitor"