name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
         ref: 'master' 
#      - run: docker-compose build
#      - run: docker-compose run web rake db:setup
#      - run: docker-compose run web bin/run-tests
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          branch: "master"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stadtratmonitor"